#!/usr/bin/env bash

# $ cat $WD/.env
# export SLACK_USER_TOKEN=...
# export SLACK_BOT_TOKEN=...

set -e

export API
export BOT_ID
export URL

API="https://slack.com/api"

main() {
    BOT_ID=$(curl "$API/auth.test?token=$SLACK_BOT_TOKEN" | jq -r ".user_id")
    URL=$(curl "$API/rtm.connect?token=$SLACK_BOT_TOKEN" | jq -r ".url")
    cargo run
}

while true; do
    cargo build
    main || true
done
