#!/usr/bin/env bash

# $ cat "$WD/.env"
# export SLACK_USER_TOKEN=...
# export SLACK_BOT_TOKEN=...

set -e

export API="https://slack.com/api"
export BOT_ID
export URL
export EXIT_CODE

while true; do
    SECONDS=0
    cargo build --release
    BOT_ID=$(curl "$API/auth.test?token=$SLACK_BOT_TOKEN" | jq -r ".user_id")
    URL=$(curl "$API/rtm.connect?token=$SLACK_BOT_TOKEN" | jq -r ".url")
    set +e
    cargo run --release
    EXIT_CODE=$?
    set -e
    # https://misc.flogisoft.com/bash/tip_colors_and_formatting
    printf "\e[1;30;47mexit\e[0m     %d\n" $EXIT_CODE
    if [ $EXIT_CODE -eq 0 ]; then
        break
    elif (( SECONDS < 5 )); then
        sleep 10
    fi
done
